# Site
#repository: sproogen/resume-theme
favicon: images/favicon.ico

# Personal info
name: JINO PL
title: DevOps/Linux Engineer
email: jinopl@yahoo.co.in


# Social links
#twitter_username: facespics
github_username:  jinopl
# dribbble_username: jekyll
# facebook_username: jekyll
# flickr_username: jekyll
instagram_username: amjino
linkedin_username: jinopl
# pinterest_username: jekyll
# youtube_username: globalmtb
# googleplus_username: +jekyll

# About Section
# about_title: About Me
about_profile_image: images/profile.jpg
about_content: | # this will include new lines to allow paragraphs
  Hi there,  am Jino, I'm a Linux system engineer with over 2 years experience. I am currently working in riosis private limited as a system engineer.
  I love to automate things to make a more efficient workflow in my company. I have worked a lot of technology to achieve efficient workflows and I am always looking for opportunities to work with something new. 
  
  I am most skilled in: <mark>Linux</mark>, <mark>Git</mark>, <mark>Jenkins</mark>, <mark>Ansible</mark>, <mark>Docker</mark> and <mark>AWS</mark> services.


# Projects Section
# projects_title: Projects

# Experience Section
# experience_title: Experience

# Education Section
# educaton_title: Education

# More Section
# more_title: A Little More About Me
more_content: | # this will include new lines to allow paragraphs
  Alongside my interests in Cloud technology some of my other interests and hobbies are:
   - Bike Riding
   - Movies
   - Study new tech stacks
   

# Footer
footer_show_references: true

# Build settings
remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag
