# Site
#repository: sproogen/resume-theme
favicon: images/favicon.ico

# Personal info
name: JINO PL
title: DevOps/Linux Engineer
email: jinopl@yahoo.co.in


# Social links
#twitter_username: facespics
github_username:  jinopl
# dribbble_username: jekyll
# facebook_username: jekyll
# flickr_username: jekyll
instagram_username: amjino
linkedin_username: jinopl
# pinterest_username: jekyll
# youtube_username: globalmtb
# googleplus_username: +jekyll

# About Section
# about_title: About Me
about_profile_image: images/profile.jpg
about_content: | # this will include new lines to allow paragraphs
  I am experienced in Linux administartion and Aspiring DevOps Engineer , Love to automate things and make my life easy and exciting.

  I am most skilled in: <mark>AWS</mark> and <mark>Eating Pizza hihihello</mark>

# Projects Section
# projects_title: Projects

# Experience Section
# experience_title: Experience

# Education Section
# educaton_title: Education

# More Section
# more_title: A Little More About Me
more_content: | # this will include new lines to allow paragraphs
  Alongside my interests in networks and software engineering some of my other interests and hobbies are:
   - Rock climbing
   - Gaming
   - Knitting
   - [Becoming a ninja](https://www.youtube.com/watch?v=vtg4o__aRMg)

# Footer
footer_show_references: true

# Build settings
remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag
